-- B0-1169 — the sweep ledger never recorded a grade.
--
-- `public.scheduled_test_items.grade` / `.confidence` were created by
-- 20260911010000_scheduled_tests_observability_b0941.sql and have been NULL on every row since:
-- nothing wrote them, and the hourly reconciler closes a child the hour its run ends, which is
-- BEFORE the run's report (and so `test_results.report_overall_grade`) is generated by the
-- `sweep-pending-reports` cron. From this ticket on the reconciler copies the grade in (on close
-- when the report already exists, otherwise on a later revisit pass). This migration is the
-- one-time back-fill for children closed before that code shipped, plus the column comments.
--
-- Data change: UPDATE only. No objects created or dropped, so `pnpm check:schema-drift` (which
-- compares catalog objects, not data or comments) is unaffected.
--
-- Measured 2026-10-08 before applying:
--   completed 215 rows (grade filled 0), failed 25 rows (grade filled 0)
--   190 completed rows whose run has report_overall_grade  → expected to change: 190
--   25 completed rows whose run has no report yet, 25 failed → stay NULL
--
-- Verify before/after:
--   select count(*) from public.scheduled_test_items i
--   join public.test_results t on t.id = i.test_run_id
--   where i.status = 'completed' and t.report_overall_grade is not null
--     and i.grade is distinct from t.report_overall_grade;
--   → 190 before, 0 after.

update public.scheduled_test_items i
set grade = t.report_overall_grade
from public.test_results t
where t.id = i.test_run_id
  and i.grade is null
  and i.status = 'completed'
  and t.report_overall_grade is not null;

comment on column public.scheduled_test_items.grade is
  'Copy of test_results.report_overall_grade for the child''s test_run_id, written by the hourly reconciler once the report exists (B0-1169). test_results stays the system of record; never derived from pass_rate.';

comment on column public.scheduled_test_items.confidence is
  'Reserved for a copy of test_results.avg_confidence once that column has a writer; as of B0-1169 nothing populates avg_confidence (the /gate route computes judgment confidence on demand from test_result_items instead), so this is NULL by design until then. Never derive a run-level confidence from per-item columns here.';
