-- B0-617: failure-queue integration for the automatic per-failure root-cause AI call.
-- Appends columns to the END of the view's SELECT list only — Postgres's
-- CREATE OR REPLACE VIEW requires existing output columns to keep their name, order,
-- and type; only new columns may be added, and only at the end. (The 20260527120000
-- migration inserted `prompt_category` mid-list, which violates that rule — this
-- migration does not repeat that mistake.)
--
-- Root cause is generated by ~/lib/tests/failure-root-cause.ts and stored in the
-- existing generic `ai_suggestions` table under entity_type
-- 'test_result_item_failure', entity_id = test_result_items.id — the same store
-- already used for per-item AI review and per-run prompt insights, just a new scope.

BEGIN;

CREATE OR REPLACE VIEW public.latest_failed_test_result_items AS
SELECT DISTINCT ON (tri.test_item_id)
  tri.id,
  tri.test_result_id,
  tri.test_item_id,
  tri.row_index,
  tri.passed,
  tri.status,
  tri.elapsed_ms,
  tri.error_message,
  tri.response_text,
  tri.response_payload,
  tri.created_at,
  ti.prompt,
  ti.prompt_category,
  ti.test_id,
  ti.row_index AS item_row_index,
  t.name AS test_name,
  tr.created_at AS run_created_at,
  rc.title AS root_cause_title,
  rc.content AS root_cause_content,
  rc.metadata ->> 'category' AS root_cause_category,
  rc.created_at AS root_cause_generated_at
FROM public.test_result_items tri
JOIN public.test_items   ti ON ti.id = tri.test_item_id
JOIN public.test_results tr ON tr.id = tri.test_result_id
JOIN public.tests         t ON  t.id = ti.test_id
LEFT JOIN LATERAL (
  SELECT s.title, s.content, s.metadata, s.created_at
  FROM public.ai_suggestions s
  WHERE s.entity_type = 'test_result_item_failure'
    AND s.entity_id = tri.id::text
  ORDER BY s.sort_order ASC, s.created_at DESC
  LIMIT 1
) rc ON true
WHERE tri.passed = false
ORDER BY tri.test_item_id, tri.created_at DESC;

GRANT SELECT ON public.latest_failed_test_result_items TO authenticated;
GRANT SELECT ON public.latest_failed_test_result_items TO service_role;

-- Search now also matches the generated root cause, so "why did this fail" is
-- searchable the same way the raw error/response text already was.
DROP FUNCTION IF EXISTS public.admin_latest_failures_count(text);

CREATE OR REPLACE FUNCTION public.admin_latest_failures_count(p_search text)
RETURNS bigint
LANGUAGE sql
STABLE
AS $$
  SELECT count(*)::bigint
  FROM public.latest_failed_test_result_items v
  WHERE trim(coalesce(p_search, '')) = ''
     OR position(lower(trim(p_search)) in lower(v.prompt)) > 0
     OR position(lower(trim(p_search)) in lower(coalesce(v.error_message, ''))) > 0
     OR position(lower(trim(p_search)) in lower(coalesce(v.response_text, ''))) > 0
     OR position(lower(trim(p_search)) in lower(coalesce(v.root_cause_content, ''))) > 0
     OR position(lower(trim(p_search)) in lower(v.test_name)) > 0;
$$;

DROP FUNCTION IF EXISTS public.admin_latest_failures_page(text, integer, integer);

CREATE OR REPLACE FUNCTION public.admin_latest_failures_page(
  p_search text,
  p_limit integer,
  p_offset integer
)
RETURNS SETOF public.latest_failed_test_result_items
LANGUAGE sql
STABLE
AS $$
  SELECT *
  FROM public.latest_failed_test_result_items v
  WHERE trim(coalesce(p_search, '')) = ''
     OR position(lower(trim(p_search)) in lower(v.prompt)) > 0
     OR position(lower(trim(p_search)) in lower(coalesce(v.error_message, ''))) > 0
     OR position(lower(trim(p_search)) in lower(coalesce(v.response_text, ''))) > 0
     OR position(lower(trim(p_search)) in lower(coalesce(v.root_cause_content, ''))) > 0
     OR position(lower(trim(p_search)) in lower(v.test_name)) > 0
  ORDER BY v.created_at DESC
  LIMIT CASE WHEN p_limit < 1 THEN 25 WHEN p_limit > 100 THEN 100 ELSE p_limit END
  OFFSET greatest(p_offset, 0);
$$;

GRANT EXECUTE ON FUNCTION public.admin_latest_failures_count(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_latest_failures_count(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_latest_failures_page(text, integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_latest_failures_page(text, integer, integer) TO service_role;

COMMIT;
