create table if not exists rag.search_embedding (
  id bigint generated by default as identity primary key,
  query_string text not null,
  query_rewritten text,
  embeddings extensions.vector(1536),
  query_count integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz default timezone('utc', now()),
  deleted_at timestamptz,
  constraint search_embedding_query_count_check check (query_count >= 0)
);

create unique index if not exists search_embedding_query_rewritten_unique_idx
  on rag.search_embedding (query_rewritten)
  where deleted_at is null
    and query_rewritten is not null;

create index if not exists search_embedding_created_at_idx
  on rag.search_embedding (created_at desc);

create trigger set_search_embedding_updated_at
before update on rag.search_embedding
for each row
execute function rag.set_updated_at();

grant select, insert, update on rag.search_embedding to service_role;

comment on table rag.search_embedding is
  'Caches semantic query embeddings used by rag search to avoid repeated embedding calls for equivalent rewritten queries.';
