import { createHash } from 'node:crypto';

import { SME_AGENT_IDS, type SmeAgentId } from '~/lib/agents/agent-registry';
import { logError, logWarn } from '~/lib/observability/logger';
import { getOpenAIClient } from '~/lib/openai/client';
import type {
  IntentValue,
  PriorTurnMessage,
} from '~/lib/orchestrator/intent-classifier';
import {
  getSemanticRouterConfidenceThreshold,
  getSemanticRouterEmbeddingModel,
  getSemanticRouterMarginThreshold,
  SEMANTIC_ROUTER_EMBEDDING_DIMENSIONS,
} from '~/lib/orchestrator/semantic-router-config';
import { semanticRouterEmbeddingsFile } from '~/lib/orchestrator/semantic-router-embeddings-source';
import {
  SEMANTIC_ROUTER_EXAMPLES,
  SEMANTIC_ROUTER_EXAMPLES_VERSION,
} from '~/lib/orchestrator/semantic-router-examples';

/**
 * B0-647 / B0-648 / B0-650 / B0-680 — the semantic intent router.
 *
 * A cheap, deterministic alternative to the LLM classifier in `intent-classifier.ts`: embed the
 * user's message once, cosine it against a hand-authored example corpus (one set per SME route),
 * and route to the best-matching route only when it is BOTH a real match (confidence threshold) and
 * a clear winner (margin threshold). Anything else is `path: 'fallback'` / `route: 'ambiguous'`,
 * which the caller is expected to treat exactly as it treats the LLM classifier's `ambiguous`.
 *
 * B0-680 — the example corpus's embeddings are PRE-COMPUTED and checked into git as
 * `semantic-router-embeddings.json` (generated by `scripts/generate-semantic-router-embeddings.ts`)
 * rather than computed via OpenAI on first boot and shared via Redis (the former B0-654 design,
 * `semantic-router-cache.ts`, now deleted). Init is a pure local load-and-validate: no OpenAI call,
 * no Redis dependency, for the example corpus. A LIVE user message is still embedded via OpenAI on
 * every call — that half of the router is unavoidable and unchanged.
 *
 * Contract, mirroring `classifyUserIntent`: this module NEVER throws. An OpenAI outage, a stale or
 * missing embeddings file, a blank message — all degrade to a fallback decision carrying a non-null
 * `error`, because a router failure must not break the turn.
 *
 * Deliberately NOT wired into the workflow here. The rollout levers
 * (`BEX_SEMANTIC_ROUTER_ENABLED` / `BEX_SEMANTIC_ROUTER_SHADOW_MODE`) and the decision to route on
 * this at all belong to the B0-649 integration.
 */

export type SemanticRouterPath = 'semantic' | 'fallback';

/** Same value space as the LLM classifier's `IntentValue`. Always 'ambiguous' when path === 'fallback'. */
export type SemanticRouteLabel = IntentValue;

export type SemanticRouteScore = { route: SmeAgentId; similarity: number };

export type SemanticRouteDecision = {
  route: SemanticRouteLabel;
  /** max similarity across routes, 0..1 */
  confidence: number;
  /** alias of confidence — both names are load-bearing for callers, so both are populated */
  similarity: number;
  /** top similarity minus runner-up similarity */
  margin: number;
  path: SemanticRouterPath;
  /** every route's score, sorted desc by similarity */
  scores: SemanticRouteScore[];
  thresholds: { confidence: number; margin: number };
  thresholdsPassed: { confidence: boolean; margin: boolean };
  /** total wall-clock ms for this call */
  latencyMs: number;
  /** ms spent on the embedding round-trip specifically (0 on a cache hit) */
  embeddingMs: number;
  /** ms spent on cosine scoring specifically — this is what the ~10ms budget really governs */
  scoringMs: number;
  embeddingModel: string;
  examplesVersion: string;
  /** non-null means degraded (API error / not initialized); path is then 'fallback' */
  error: string | null;
};

export type SemanticRouterInitResult = {
  examplesVersion: string;
  embeddingModel: string;
  routeCount: number;
  exampleCount: number;
  /** 'static' = loaded (this call) from the pre-computed `semantic-router-embeddings.json`; 'memory' = a warm process reused the corpus already loaded by an earlier call. */
  source: 'static' | 'memory';
  errors: string[];
};

// ---------------------------------------------------------------------------------------------
// Timing helpers
// ---------------------------------------------------------------------------------------------

/**
 * `performance.now()` rather than `Date.now()`: the cosine pass is well under a millisecond, and a
 * whole-millisecond clock would report it as "0ms" and make the latency budget unmeasurable.
 */
const nowMs = (): number => performance.now();

/** Sub-millisecond precision kept (3dp) so `scoringMs` is a real number, not a rounded-to-zero one. */
const roundMs = (ms: number): number => Math.round(ms * 1000) / 1000;

/**
 * Bounded ceiling so a hung OpenAI call degrades instead of hanging the turn. Mirrors
 * `withRouterTimeout`. Only guards the LIVE per-message embedding call now — the example corpus is
 * pre-computed (B0-680) and never calls OpenAI at init.
 */
const EMBEDDING_TIMEOUT_MS = 5_000;

async function withSemanticRouterTimeout<T>(
  budgetMs: number,
  label: string,
  run: (signal: AbortSignal) => Promise<T>,
): Promise<T> {
  const controller = new AbortController();
  const budget = Math.max(0, Math.floor(budgetMs));
  let timer: ReturnType<typeof setTimeout> | undefined;

  try {
    return await Promise.race([
      run(controller.signal),
      new Promise<never>((_resolve, reject) => {
        timer = setTimeout(() => {
          controller.abort();
          reject(new Error(`${label} exceeded its ${budget}ms timeout`));
        }, budget);
      }),
    ]);
  } finally {
    if (timer) clearTimeout(timer);
  }
}

// ---------------------------------------------------------------------------------------------
// Embedding (B0-647) — LIVE messages only since B0-680; the example corpus is pre-computed.
// ---------------------------------------------------------------------------------------------

/**
 * Why not `createEmbedding()` from `~/lib/rag/embeddings.ts`: that helper is tuned for the RAG
 * corpus's batch-sync jobs, and this call sits directly on a user's turn — the router talks to
 * `getOpenAIClient()` directly so it owns its own timeout/retry policy, and enforces the SAME
 * 3072-dimension invariant `createEmbedding` does (see `SEMANTIC_ROUTER_EMBEDDING_DIMENSIONS`).
 * That invariant is also why `SEMANTIC_ROUTER_EMBEDDING_MODEL` only accepts 3072-dim models.
 *
 * Still accepts a batch of inputs (not just one string) even though every live call today embeds a
 * single message — the pre-computed example corpus used to be built through this same function
 * before B0-680, and keeping the signature batched costs nothing and avoids a needless second code
 * path if a future caller ever needs to embed more than one string at once.
 */
async function embedBatch(
  inputs: readonly string[],
  model: string,
  signal: AbortSignal,
): Promise<number[][]> {
  const client = getOpenAIClient();
  const response = await client.embeddings.create(
    { model, input: [...inputs] },
    // maxRetries 0 for the same reason the LLM router uses it: the SDK's backoff+replay can never
    // finish inside our budget, so a transient failure would just become a guaranteed timeout.
    { signal, maxRetries: 0 },
  );

  if (response.data.length !== inputs.length) {
    throw new Error(
      `Expected ${inputs.length} embeddings from OpenAI but received ${response.data.length}.`,
    );
  }

  return response.data.map((item, index) => {
    const vector = item.embedding;
    if (
      !Array.isArray(vector) ||
      vector.length !== SEMANTIC_ROUTER_EMBEDDING_DIMENSIONS
    ) {
      throw new Error(
        `Embedding ${index} had ${vector?.length ?? 0} dimensions; expected ${SEMANTIC_ROUTER_EMBEDDING_DIMENSIONS}.`,
      );
    }
    return vector;
  });
}

// ---------------------------------------------------------------------------------------------
// Similarity math (B0-648)
// ---------------------------------------------------------------------------------------------

/** L2 norm. Returned as 0 for a zero/degenerate vector so callers can reject it explicitly. */
export function vectorNorm(vector: readonly number[]): number {
  let sum = 0;
  for (const value of vector) sum += value * value;
  const norm = Math.sqrt(sum);
  return Number.isFinite(norm) ? norm : 0;
}

/**
 * Cosine similarity with PRE-COMPUTED norms — the hot path. OpenAI returns L2-normalized vectors,
 * so cosine reduces to a plain dot product, but we still divide by the stored norms rather than
 * assuming: a JSON round-trip through `semantic-router-embeddings.json`, or a future non-OpenAI
 * provider, can leave a norm that is not exactly 1. A zero/NaN norm or a length mismatch yields 0
 * ("no match") instead of NaN, which would otherwise silently win or lose comparisons.
 */
export function cosineSimilarityWithNorms(
  a: readonly number[],
  normA: number,
  b: readonly number[],
  normB: number,
): number {
  if (a.length !== b.length || a.length === 0) return 0;
  if (
    !Number.isFinite(normA) ||
    !Number.isFinite(normB) ||
    normA <= 0 ||
    normB <= 0
  )
    return 0;

  let dot = 0;
  for (let i = 0; i < a.length; i += 1) dot += a[i]! * b[i]!;

  const similarity = dot / (normA * normB);
  return Number.isFinite(similarity) ? similarity : 0;
}

/** Convenience wrapper that derives both norms. Used by tests and any non-hot-path caller. */
export function cosineSimilarity(
  a: readonly number[],
  b: readonly number[],
): number {
  return cosineSimilarityWithNorms(a, vectorNorm(a), b, vectorNorm(b));
}

/** One route's embedded example corpus, with norms cached so scoring is pure multiply-add. */
export type RouteVectors = {
  route: SmeAgentId;
  examples: readonly string[];
  vectors: readonly number[][];
  norms: readonly number[];
};

const clamp01 = (n: number): number => Math.max(0, Math.min(1, n));

/**
 * Score every route as the MAXIMUM cosine similarity over that route's examples, then sort desc.
 *
 * Max, not mean, on purpose: the corpus is a set of DISTINCT phrasings, so a message about
 * burnishing matches the burnishing example strongly and the wood-floor-refinish example weakly.
 * Averaging would let a route's own breadth dilute its best evidence — and would make adding a
 * good-but-unrelated example to a route measurably WORSE for that route, which is a perverse
 * incentive for anyone maintaining `semantic-router-examples.ts`. One strongly-matching example is
 * the signal we want; the margin threshold is what protects us from a lucky single match.
 *
 * Similarities are clamped into [0,1]: a negative cosine is "less than no match", and `confidence`
 * is documented as 0..1. In practice OpenAI text embeddings of English sentences essentially never
 * go negative, so this clamp changes nothing about real ordering.
 */
export function scoreRoutes(
  messageVector: readonly number[],
  messageNorm: number,
  routes: readonly RouteVectors[],
): SemanticRouteScore[] {
  const scores: SemanticRouteScore[] = [];

  for (const route of routes) {
    let best = 0;
    for (let i = 0; i < route.vectors.length; i += 1) {
      const similarity = cosineSimilarityWithNorms(
        messageVector,
        messageNorm,
        route.vectors[i]!,
        route.norms[i]!,
      );
      if (similarity > best) best = similarity;
    }
    scores.push({ route: route.route, similarity: clamp01(best) });
  }

  return scores.sort((a, b) => b.similarity - a.similarity);
}

// ---------------------------------------------------------------------------------------------
// Initialization (B0-647 / B0-680)
// ---------------------------------------------------------------------------------------------

/** Envelope format this build knows how to read. Bump alongside a breaking change to the file's shape. */
const SEMANTIC_ROUTER_EMBEDDINGS_FILE_FORMAT = 1;

type RouterState = {
  examplesVersion: string;
  embeddingModel: string;
  routes: RouteVectors[];
};

let state: RouterState | null = null;
/**
 * Memoized in-flight init. Next.js 16's App Router has no reliable single process-start hook that
 * fires in dev, in a serverless function, and in a long-lived node server alike (instrumentation
 * hooks run per-runtime and not at all for some entrypoints), so "pre-compute at startup" is
 * implemented as lazy-and-idempotent: the FIRST `classifyUserIntentSemantic` awaits this promise,
 * every later call and every concurrent caller shares it, and the resulting vectors live in module
 * scope for the life of the process — surviving across requests exactly as a startup hook would,
 * without depending on one existing.
 */
let initPromise: Promise<SemanticRouterInitResult> | null = null;
let lastInitResult: SemanticRouterInitResult | null = null;

function toRouteVectors(
  route: SmeAgentId,
  examples: readonly string[],
  vectors: readonly number[][],
): RouteVectors {
  return {
    route,
    examples,
    vectors,
    norms: vectors.map(vectorNorm),
  };
}

/**
 * Validate one route's entry from the pre-computed file against the LIVE `SEMANTIC_ROUTER_EXAMPLES`
 * corpus before trusting a single number in it — mirrors the diligence the old Redis cache payload
 * validation applied (`semantic-router-cache.ts`, deleted by B0-680), just against a file instead of
 * a network payload. A stale or corrupt entry is skipped (this route falls back to `ambiguous`
 * routing, same as an unreachable OpenAI call used to do), never trusted.
 */
function validateRouteEntry(
  examples: readonly string[],
  entry: { examples: string[]; vectors: number[][] } | undefined,
  dimensions: number,
): { vectors: number[][] } | { error: string } {
  if (!entry) return { error: 'missing from the embeddings file' };
  if (!Array.isArray(entry.examples) || entry.examples.length !== examples.length) {
    return { error: 'example count does not match semantic-router-examples.ts' };
  }
  for (let i = 0; i < examples.length; i += 1) {
    if (entry.examples[i] !== examples[i]) {
      return {
        error: `example text at index ${i} does not match semantic-router-examples.ts — regenerate via scripts/generate-semantic-router-embeddings.ts`,
      };
    }
  }
  if (!Array.isArray(entry.vectors) || entry.vectors.length !== examples.length) {
    return { error: 'vector count does not match its example count' };
  }
  for (const vector of entry.vectors) {
    if (
      !Array.isArray(vector) ||
      vector.length !== dimensions ||
      !vector.every((value) => Number.isFinite(value))
    ) {
      return { error: 'a stored vector has the wrong dimension or a non-finite value' };
    }
  }
  return { vectors: entry.vectors };
}

/**
 * Load and validate the pre-computed corpus embeddings from `semantic-router-embeddings.json`
 * (B0-680). Pure and synchronous — no OpenAI call, no Redis call, just local validation — but kept
 * `async` so its call site (`runInit`) does not have to change shape depending on which init
 * strategy is active.
 *
 * Every failure mode degrades to "skip this route" / "skip the whole file" rather than throwing:
 * a bad file must never crash the app at import time, only leave the router in the same degraded
 * fallback state an unreachable OpenAI call used to produce.
 */
function loadPrecomputedRoutes(
  embeddingModel: string,
  examplesVersion: string,
): { routes: RouteVectors[]; errors: string[] } {
  const errors: string[] = [];
  const routes: RouteVectors[] = [];
  const file = semanticRouterEmbeddingsFile;

  if (file.format !== SEMANTIC_ROUTER_EMBEDDINGS_FILE_FORMAT) {
    errors.push(
      `semantic-router-embeddings.json has format ${file.format}, expected ${SEMANTIC_ROUTER_EMBEDDINGS_FILE_FORMAT}`,
    );
    return { routes, errors };
  }
  if (file.examplesVersion !== examplesVersion) {
    errors.push(
      `semantic-router-embeddings.json was generated for examples version ${file.examplesVersion}, code is at ${examplesVersion} — regenerate via scripts/generate-semantic-router-embeddings.ts`,
    );
    return { routes, errors };
  }
  if (file.embeddingModel !== embeddingModel) {
    errors.push(
      `semantic-router-embeddings.json was generated with model ${file.embeddingModel}, current setting is ${embeddingModel}`,
    );
    return { routes, errors };
  }
  if (file.dimensions !== SEMANTIC_ROUTER_EMBEDDING_DIMENSIONS) {
    errors.push(
      `semantic-router-embeddings.json has ${file.dimensions} dimensions, expected ${SEMANTIC_ROUTER_EMBEDDING_DIMENSIONS}`,
    );
    return { routes, errors };
  }

  for (const route of SME_AGENT_IDS) {
    const examples = SEMANTIC_ROUTER_EXAMPLES[route] ?? [];
    if (examples.length === 0) {
      errors.push(`route ${route} has no examples`);
      continue;
    }

    const validated = validateRouteEntry(
      examples,
      file.routes[route],
      SEMANTIC_ROUTER_EMBEDDING_DIMENSIONS,
    );
    if ('error' in validated) {
      errors.push(`route ${route}: ${validated.error}`);
      continue;
    }
    routes.push(toRouteVectors(route, examples, validated.vectors));
  }

  return { routes, errors };
}

async function runInit(): Promise<SemanticRouterInitResult> {
  const embeddingModel = await getSemanticRouterEmbeddingModel();
  const examplesVersion = SEMANTIC_ROUTER_EXAMPLES_VERSION;
  const { routes, errors } = loadPrecomputedRoutes(embeddingModel, examplesVersion);

  const result: SemanticRouterInitResult = {
    examplesVersion,
    embeddingModel,
    routeCount: routes.length,
    exampleCount: routes.reduce((total, r) => total + r.vectors.length, 0),
    // 'static' whenever routes were loaded from the pre-computed file this call. ('memory' is
    // reported by `initSemanticRouter` for a warm process that skips this function entirely.)
    source: 'static',
    errors,
  };

  if (routes.length > 0) {
    state = { examplesVersion, embeddingModel, routes };
  }

  if (errors.length > 0) {
    logWarn('bex.semantic_router.init_degraded', {
      routeCount: result.routeCount,
      exampleCount: result.exampleCount,
      errors: errors.join('; '),
    });
  }

  lastInitResult = result;
  return result;
}

/**
 * Load (or re-use the in-memory copy of) every example embedding from the pre-computed file.
 * Idempotent and safe to call concurrently — concurrent callers share one in-flight promise, and a
 * warm process returns immediately with `source: 'memory'`. Never throws: a total failure resolves
 * with `routeCount: 0` and the reasons in `errors`, and clears the memo so the NEXT call can retry
 * (a permanently memoized failure would leave the router dead for the life of the process — this
 * matters less now that there is no network call to retry, but a corrected/regenerated file should
 * not require a process restart to pick up in a long-lived dev server).
 */
export async function initSemanticRouter(): Promise<SemanticRouterInitResult> {
  if (state && lastInitResult) {
    return { ...lastInitResult, source: 'memory' };
  }
  if (initPromise) return initPromise;

  initPromise = runInit().then((result) => {
    if (!state) initPromise = null;
    return result;
  });

  return initPromise;
}

// ---------------------------------------------------------------------------------------------
// Live message embedding cache (B0-648)
// ---------------------------------------------------------------------------------------------

/**
 * Same design as `intent-classifier.ts`'s result cache: promise-valued so concurrent callers share
 * one round-trip, TTL + max-entries so a long-lived process cannot grow unbounded, failures evicted
 * so a transient API error is not served for the rest of the TTL.
 *
 * This is what makes the "warm path" genuinely fast — on a hit the whole call is the cosine pass.
 */
export const SEMANTIC_ROUTER_CACHE_TTL_MS = 5 * 60_000;
const MAX_CACHE_ENTRIES = 256;

type EmbeddingCacheEntry = {
  expiresAt: number;
  promise: Promise<{ vector: number[]; norm: number }>;
};

const embeddingCache = new Map<string, EmbeddingCacheEntry>();
const cacheStats = { hits: 0, misses: 0 };

/**
 * `hash(model + examplesVersion + message + prior-turn-ids)`.
 *
 * Prior-turn ids are part of the key even though today only the message text is embedded (see
 * `classifyUserIntentSemantic`) — this keeps the key semantics identical to
 * `computeIntentClassifierCacheKey`, so a shadow-mode comparison of the two routers sees the same
 * hit/miss boundaries, and so folding conversational context into the embedded text later cannot
 * introduce a stale-cache bug.
 */
export function computeSemanticRouterCacheKey(
  message: string,
  priorMessages: PriorTurnMessage[] = [],
  embeddingModel: string,
): string {
  const ids = priorMessages.map((m) => m.id);
  const canonical = [
    `model:${embeddingModel}`,
    `examples:${SEMANTIC_ROUTER_EXAMPLES_VERSION}`,
    `msg:${message.length}:${message}`,
    `ids:${ids.length}:${ids.join(',')}`,
  ].join('|');
  return createHash('sha256').update(canonical, 'utf8').digest('hex');
}

function pruneCache(now: number): void {
  for (const [key, entry] of embeddingCache) {
    if (entry.expiresAt <= now) embeddingCache.delete(key);
  }
  while (embeddingCache.size >= MAX_CACHE_ENTRIES) {
    const oldest = embeddingCache.keys().next();
    if (oldest.done) break;
    embeddingCache.delete(oldest.value);
  }
}

/** Observability/test helper: message-embedding cache counters. */
export function getSemanticRouterCacheStats(): {
  hits: number;
  misses: number;
  size: number;
} {
  return {
    hits: cacheStats.hits,
    misses: cacheStats.misses,
    size: embeddingCache.size,
  };
}

/**
 * Test helper: forget the example corpus, the init memo, and every cached message embedding, so a
 * test can re-init against a different mock without leaking state across cases.
 */
export function resetSemanticRouterForTest(): void {
  state = null;
  initPromise = null;
  lastInitResult = null;
  embeddingCache.clear();
  cacheStats.hits = 0;
  cacheStats.misses = 0;
}

// ---------------------------------------------------------------------------------------------
// The decision (B0-648 / B0-650)
// ---------------------------------------------------------------------------------------------

type DecisionInput = {
  scores: SemanticRouteScore[];
  thresholds: { confidence: number; margin: number };
  latencyMs: number;
  embeddingMs: number;
  scoringMs: number;
  embeddingModel: string;
  examplesVersion: string;
  error: string | null;
};

/**
 * B0-650 — routing succeeds ONLY if BOTH gates pass: the top score clears the confidence threshold
 * ("is this a real match at all?") AND beats the runner-up by the margin threshold ("is it a clear
 * winner?"). Either failure, or any `error`, returns `path: 'fallback'` with `route: 'ambiguous'` —
 * and the decision still carries every score, both thresholds, and which gate failed, so a fallback
 * is diagnosable from the persisted trace rather than being an unexplained shrug.
 *
 * With a single route present the runner-up is treated as 0, so `margin === confidence`. That is the
 * conservative reading: with nothing to compare against there is no evidence of a *clear* winner
 * beyond the absolute score itself.
 */
export function buildSemanticRouteDecision({
  scores,
  thresholds,
  latencyMs,
  embeddingMs,
  scoringMs,
  embeddingModel,
  examplesVersion,
  error,
}: DecisionInput): SemanticRouteDecision {
  const top = scores[0];
  const confidence = top ? clamp01(top.similarity) : 0;
  const runnerUp = scores[1]?.similarity ?? 0;
  const margin = Math.max(0, confidence - runnerUp);

  const confidencePassed = Boolean(top) && confidence >= thresholds.confidence;
  const marginPassed = Boolean(top) && margin >= thresholds.margin;
  const routed =
    error === null && top !== undefined && confidencePassed && marginPassed;

  return {
    route: routed ? top!.route : 'ambiguous',
    confidence,
    similarity: confidence,
    margin,
    path: routed ? 'semantic' : 'fallback',
    scores,
    thresholds,
    thresholdsPassed: { confidence: confidencePassed, margin: marginPassed },
    latencyMs: roundMs(latencyMs),
    embeddingMs: roundMs(embeddingMs),
    scoringMs: roundMs(scoringMs),
    embeddingModel,
    examplesVersion,
    error,
  };
}

async function resolveThresholds(): Promise<{
  confidence: number;
  margin: number;
}> {
  const [confidence, margin] = await Promise.all([
    getSemanticRouterConfidenceThreshold(),
    getSemanticRouterMarginThreshold(),
  ]);
  return { confidence, margin };
}

/**
 * B0-648 — classify a message by semantic similarity to the example corpus.
 *
 * `priorMessages` is accepted for signature parity with `classifyUserIntent` and participates in the
 * embedding cache key, but the embedded text is the CURRENT message alone: the example corpus is
 * made of single-utterance vectors, so concatenating history would pull the message vector away from
 * the space the corpus lives in and depress every score. Handling a context-dependent follow-up
 * ("and the shower stalls?") stays the LLM classifier's job.
 *
 * Latency, honestly: the ~10ms budget in the ticket applies to `scoringMs` (the cosine pass) and to
 * the whole warm call when the message embedding is cached (`embeddingMs === 0`). A COLD call is
 * dominated by the OpenAI embedding round-trip, which is tens to hundreds of ms and cannot be
 * inside 10ms; `embeddingMs` reports it truthfully rather than hiding it in a blended number.
 */
export async function classifyUserIntentSemantic(
  message: string,
  priorMessages: PriorTurnMessage[] = [],
): Promise<SemanticRouteDecision> {
  const startedAt = nowMs();
  const thresholds = await resolveThresholds();

  const degraded = (
    error: string,
    embeddingModel: string,
    embeddingMs = 0,
  ): SemanticRouteDecision =>
    buildSemanticRouteDecision({
      scores: [],
      thresholds,
      latencyMs: nowMs() - startedAt,
      embeddingMs,
      scoringMs: 0,
      embeddingModel,
      examplesVersion: SEMANTIC_ROUTER_EXAMPLES_VERSION,
      error,
    });

  const trimmed = message.trim();
  if (trimmed.length === 0) {
    return degraded('empty_message', await getSemanticRouterEmbeddingModel());
  }

  const init = await initSemanticRouter();
  const active = state;
  if (!active || active.routes.length === 0) {
    return degraded(
      init.errors[0] ?? 'semantic_router_not_initialized',
      init.embeddingModel,
    );
  }

  const cacheKey = computeSemanticRouterCacheKey(
    trimmed,
    priorMessages,
    active.embeddingModel,
  );
  const now = Date.now();
  const existing = embeddingCache.get(cacheKey);

  let embedded: { vector: number[]; norm: number };
  let embeddingMs = 0;

  if (existing && existing.expiresAt > now) {
    cacheStats.hits += 1;
    try {
      embedded = await existing.promise;
    } catch (error: unknown) {
      // Can only happen if a concurrent miss is still in flight and fails; treat as degraded.
      const reason = error instanceof Error ? error.message : String(error);
      return degraded(reason, active.embeddingModel);
    }
  } else {
    pruneCache(now);
    cacheStats.misses += 1;

    const promise = withSemanticRouterTimeout(
      EMBEDDING_TIMEOUT_MS,
      'classifyUserIntentSemantic',
      (signal) => embedBatch([trimmed], active.embeddingModel, signal),
    ).then(([vector]) => {
      const resolved = vector!;
      return { vector: resolved, norm: vectorNorm(resolved) };
    });

    embeddingCache.set(cacheKey, {
      expiresAt: now + SEMANTIC_ROUTER_CACHE_TTL_MS,
      promise,
    });

    const embeddingStartedAt = nowMs();
    try {
      embedded = await promise;
    } catch (error: unknown) {
      // Never cache a failure: a cached transient timeout would keep routing degraded for the TTL.
      embeddingCache.delete(cacheKey);
      const reason = error instanceof Error ? error.message : String(error);
      logError('bex.semantic_router.fallback', { reason });
      return degraded(
        reason,
        active.embeddingModel,
        nowMs() - embeddingStartedAt,
      );
    }
    embeddingMs = nowMs() - embeddingStartedAt;
  }

  if (embedded.norm <= 0) {
    return degraded(
      'zero_norm_message_embedding',
      active.embeddingModel,
      embeddingMs,
    );
  }

  const scoringStartedAt = nowMs();
  const scores = scoreRoutes(embedded.vector, embedded.norm, active.routes);
  const scoringMs = nowMs() - scoringStartedAt;

  return buildSemanticRouteDecision({
    scores,
    thresholds,
    latencyMs: nowMs() - startedAt,
    embeddingMs,
    scoringMs,
    embeddingModel: active.embeddingModel,
    examplesVersion: active.examplesVersion,
    error: null,
  });
}
